### ISSUE TITLE
Crash with 1.20.1 on a server

### ISSUE THREAD

**Issue by HikariYlan** [ejektaflex/Kambrik#22] opened 2023-07-19 16:25 UTC
processRunning
2023-07-19 17:21:29,326 main WARN Advanced terminal features are not available in this environment
[17:21:29] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 47.1.33, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412, nogui]
[17:21:29] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 19.0.2 by Eclipse Adoptium; OS Linux arch amd64 version 5.4.0-137-generic
[17:21:29] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: ImmediateWindowProvider not loading because launch target is forgeserver
[17:21:29] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/sid_5211094/minecraft_forge_1201/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2365!/ Service=ModLauncher Env=SERVER
[17:21:30] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/sid_5211094/minecraft_forge_1201/libraries/net/minecraftforge/fmlcore/1.20.1-47.1.33/fmlcore-1.20.1-47.1.33.jar is missing mods.toml file
[17:21:30] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/sid_5211094/minecraft_forge_1201/libraries/net/minecraftforge/javafmllanguage/1.20.1-47.1.33/javafmllanguage-1.20.1-47.1.33.jar is missing mods.toml file
[17:21:30] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/sid_5211094/minecraft_forge_1201/libraries/net/minecraftforge/lowcodelanguage/1.20.1-47.1.33/lowcodelanguage-1.20.1-47.1.33.jar is missing mods.toml file
[17:21:30] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/sid_5211094/minecraft_forge_1201/libraries/net/minecraftforge/mclanguage/1.20.1-47.1.33/mclanguage-1.20.1-47.1.33.jar is missing mods.toml file
[17:21:30] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 3 dependencies adding them to mods collection
[17:21:31] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[17:21:31] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments [nogui]
[17:21:37] [modloading-worker-0/INFO] [Collective/]: Loading Collective version 6.65.
[17:21:37] [modloading-worker-0/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 47.1.33, for MC 1.20.1 with MCP 20230612.114412
[17:21:37] [modloading-worker-0/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v47.1.33 Initialized
[17:21:37] [modloading-worker-0/INFO] [de.ar.ne.fo.NetworkManagerImpl/]: Registering C2S receiver with id architectury:sync_ids
[17:21:37] [modloading-worker-0/INFO] [th.ko.te.KotlinForForge/]: Kotlin For Forge Enabled!
Service loaders found: [io.ejekta.kambrik.bridge.KambrikSharedApiForge@5f614bb5]
[17:21:37] [modloading-worker-0/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/KeyMapping for invalid dist DEDICATED_SERVER
[17:21:37] [modloading-worker-0/ERROR] [ne.mi.ev.EventSubclassTransformer/EVENTBUS]: An error occurred building event handler
java.lang.RuntimeException: Attempted to load class net/minecraft/client/KeyMapping for invalid dist DEDICATED_SERVER
at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.1.33.jar%2369!/:1.0] {}
at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?] {}
at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?] {}
at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?] {}
at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:97) ~[eventbus-6.0.5.jar%2352!/:?] {}
at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:48) ~[eventbus-6.0.5.jar%2352!/:?] {}
at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:26) ~[eventbus-6.0.5.jar%2352!/:?] {}
at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:32) ~[eventbus-6.0.5.jar%2352!/:6.0.5+6.0.5+master.eb8e549b] {}
at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?] {}
at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?] {}
at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?] {}
at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {}
at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:?] {}
at java.lang.Class.privateGetPublicMethods(Unknown Source) ~[?:?] {}
at java.lang.Class.getMethods(Unknown Source) ~[?:?] {}
at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:100) ~[eventbus-6.0.5.jar%2352!/:?] {}
at net.minecraftforge.eventbus.EventBus.register(EventBus.java:128) ~[eventbus-6.0.5.jar%2352!/:?] {}
at io.ejekta.kambrik.KambrikModForge.<clinit>(KambrikModForge.kt:40) ~[Kambrik-6.1.0+1.20.1-forge.jar%23124!/:?] {re:classloading}
at jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?] {}
at jdk.internal.misc.Unsafe.ensureClassInitialized(Unknown Source) ~[?:?] {}
at jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(Unknown Source) ~[?:?] {}
at jdk.internal.reflect.MethodHandleAccessorFactory.newFieldAccessor(Unknown Source) ~[?:?] {}
at jdk.internal.reflect.ReflectionFactory.newFieldAccessor(Unknown Source) ~[?:?] {}
at java.lang.reflect.Field.acquireFieldAccessor(Unknown Source) ~[?:?] {}
at java.lang.reflect.Field.getFieldAccessor(Unknown Source) ~[?:?] {}
at java.lang.reflect.Field.get(Unknown Source) ~[?:?] {}
at kotlin.reflect.jvm.internal.KClassImpl$Data$objectInstance$2.invoke(KClassImpl.kt:117) ~[kotlinforforge-4.4.0-all.jar%23125!/:?] {}
at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:63) ~[kotlinforforge-4.4.0-all.jar%23125!/:?] {}
at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32) ~[kotlinforforge-4.4.0-all.jar%23125!/:?] {}
at kotlin.reflect.jvm.internal.KClassImpl$Data.getObjectInstance(KClassImpl.kt:108) ~[kotlinforforge-4.4.0-all.jar%23125!/:?] {}
at kotlin.reflect.jvm.internal.KClassImpl.getObjectInstance(KClassImpl.kt:242) ~[kotlinforforge-4.4.0-all.jar%23125!/:?] {}
at thedarkcolour.kotlinforforge.KotlinModContainer.constructMod(KotlinModContainer.kt:73) ~[kfflang-4.4.0.jar%23142!/:4.4.0] {}
at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.1.33.jar%23132!/:?] {}
at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}
rate limit exceeded
processEnded
consoleConnectionLost
consoleConnectionMade
processRunning
2023-07-19 17:22:22,843 main WARN Advanced terminal features are not available in this environment
[17:22:23] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 47.1.33, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412, nogui]
[17:22:23] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 19.0.2 by Eclipse Adoptium; OS Linux arch amd64 version 5.4.0-137-generic
[17:22:23] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: ImmediateWindowProvider not loading because launch target is forgeserver
[17:22:23] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/home/sid_5211094/minecraft_forge_1201/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2365!/ Service=ModLauncher Env=SERVER
[17:22:23] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/sid_5211094/minecraft_forge_1201/libraries/net/minecraftforge/fmlcore/1.20.1-47.1.33/fmlcore-1.20.1-47.1.33.jar is missing mods.toml file
[17:22:23] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/sid_5211094/minecraft_forge_1201/libraries/net/minecraftforge/javafmllanguage/1.20.1-47.1.33/javafmllanguage-1.20.1-47.1.33.jar is missing mods.toml file
[17:22:23] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/sid_5211094/minecraft_forge_1201/libraries/net/minecraftforge/lowcodelanguage/1.20.1-47.1.33/lowcodelanguage-1.20.1-47.1.33.jar is missing mods.toml file
[17:22:23] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file /home/sid_5211094/minecraft_forge_1201/libraries/net/minecraftforge/mclanguage/1.20.1-47.1.33/mclanguage-1.20.1-47.1.33.jar is missing mods.toml file
[17:22:23] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: Found 3 dependencies adding them to mods collection
[17:22:25] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[17:22:25] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeserver' with arguments [nogui]
[17:22:31] [modloading-worker-0/INFO] [Collective/]: Loading Collective version 6.65.
[17:22:31] [modloading-worker-0/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 47.1.33, for MC 1.20.1 with MCP 20230612.114412
[17:22:31] [modloading-worker-0/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v47.1.33 Initialized
[17:22:31] [modloading-worker-0/INFO] [de.ar.ne.fo.NetworkManagerImpl/]: Registering C2S receiver with id architectury:sync_ids
[17:22:32] [modloading-worker-0/INFO] [th.ko.te.KotlinForForge/]: Kotlin For Forge Enabled!
Service loaders found: [io.ejekta.kambrik.bridge.KambrikSharedApiForge@6a6fc164]
[17:22:32] [modloading-worker-0/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/KeyMapping for invalid dist DEDICATED_SERVER
[17:22:32] [modloading-worker-0/ERROR] [ne.mi.ev.EventSubclassTransformer/EVENTBUS]: An error occurred building event handler
java.lang.RuntimeException: Attempted to load class net/minecraft/client/KeyMapping for invalid dist DEDICATED_SERVER
at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.20.1-47.1.33.jar%2369!/:1.0] {}
at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?] {}
at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?] {}
at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?] {}
at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
at net.minecraftforge.eventbus.EventSubclassTransformer.buildEvents(EventSubclassTransformer.java:97) ~[eventbus-6.0.5.jar%2352!/:?] {}
at net.minecraftforge.eventbus.EventSubclassTransformer.transform(EventSubclassTransformer.java:48) ~[eventbus-6.0.5.jar%2352!/:?] {}
at net.minecraftforge.eventbus.EventBusEngine.processClass(EventBusEngine.java:26) ~[eventbus-6.0.5.jar%2352!/:?] {}
at net.minecraftforge.eventbus.service.ModLauncherService.processClassWithFlags(ModLauncherService.java:32) ~[eventbus-6.0.5.jar%2352!/:6.0.5+6.0.5+master.eb8e549b] {}
at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-10.0.9.jar%2355!/:?] {}
at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-10.0.9.jar%2355!/:?] {}
at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-10.0.9.jar%2355!/:?] {}
at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-2.1.10.jar:?] {}
at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-2.1.10.jar:?] {}
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?] {}
at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {}
at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:?] {}
at java.lang.Class.privateGetPublicMethods(Unknown Source) ~[?:?] {}
at java.lang.Class.getMethods(Unknown Source) ~[?:?] {}
at net.minecraftforge.eventbus.EventBus.registerObject(EventBus.java:100) ~[eventbus-6.0.5.jar%2352!/:?] {}
at net.minecraftforge.eventbus.EventBus.register(EventBus.java:128) ~[eventbus-6.0.5.jar%2352!/:?] {}
at io.ejekta.kambrik.KambrikModForge.<clinit>(KambrikModForge.kt:40) ~[Kambrik-6.1.0+1.20.1-forge.jar%23124!/:?] {re:classloading}
at jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method) ~[?:?] {}
at jdk.internal.misc.Unsafe.ensureClassInitialized(Unknown Source) ~[?:?] {}
at jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(Unknown Source) ~[?:?] {}
at jdk.internal.reflect.MethodHandleAccessorFactory.newFieldAccessor(Unknown Source) ~[?:?] {}
at jdk.internal.reflect.ReflectionFactory.newFieldAccessor(Unknown Source) ~[?:?] {}
at java.lang.reflect.Field.acquireFieldAccessor(Unknown Source) ~[?:?] {}
at java.lang.reflect.Field.getFieldAccessor(Unknown Source) ~[?:?] {}
at java.lang.reflect.Field.get(Unknown Source) ~[?:?] {}
at kotlin.reflect.jvm.internal.KClassImpl$Data$objectInstance$2.invoke(KClassImpl.kt:117) ~[kotlinforforge-4.4.0-all.jar%23125!/:?] {}
at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:63) ~[kotlinforforge-4.4.0-all.jar%23125!/:?] {}
at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32) ~[kotlinforforge-4.4.0-all.jar%23125!/:?] {}
at kotlin.reflect.jvm.internal.KClassImpl$Data.getObjectInstance(KClassImpl.kt:108) ~[kotlinforforge-4.4.0-all.jar%23125!/:?] {}
at kotlin.reflect.jvm.internal.KClassImpl.getObjectInstance(KClassImpl.kt:242) ~[kotlinforforge-4.4.0-all.jar%23125!/:?] {}
at thedarkcolour.kotlinforforge.KotlinModContainer.constructMod(KotlinModContainer.kt:73) ~[kfflang-4.4.0.jar%23142!/:4.4.0] {}
at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:123) ~[fmlcore-1.20.1-47.1.33.jar%23132!/:?] {}
at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {}
at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {}
at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}
[17:22:32] [modloading-worker-0/ERROR] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/KeyMapping for invalid dist DEDICATED_SERVER
rate limit exceeded
Negative index in crash report handler (16/18)
processEnded
consoleConnectionLost

The logs from when I click on "Start" to the moment it stops
It's the same problem that the issue #21

**Comment by ejektaflex** [comment] 2023-07-19 16:27
Closing as duplicate of #21 , but thanks for the report! I've figured out the cause and I'll try to get that fixed today.

**Closed as completed by ejektaflex** 2023-07-19 16:27 UTC
