### ISSUE TITLE
3.0.1-1.18 Crash on startup

### ISSUE THREAD

**Issue by ClaudiusMinimus** [ejektaflex/Kambrik#11] opened 2022-01-08 11:37 UTC
I am in the process of updating my pack, [99 Mods on the Wall: Fabric Edition](https://www.curseforge.com/minecraft/modpacks/ninety-nice-99-mods-on-the-wall-fabric-edition). I updated Kambrik to 3.0.1-1.18 and it crashes the client. However, when I revert to 3.0.0-1.18 it runs fine.

https://crashy.net/urs4tnqTSTcPokUAyK1D
or
https://crashy.net/urs4tnqTSTcPokUAyK1D?raw

**Comment by ejektaflex** [comment] 2022-01-09 07:02
Fixed, duplicate of #10

**Closed by ejektaflex** 2022-01-09 07:02 UTC

**Comment by isXander** [comment] 2022-01-09 22:38
I also have this issue with my mod. What actually is the fix? @ejektaflex

**Comment by ejektaflex** [comment] 2022-01-11 07:33
@isXander is this a mod you've already released? If so, rebuild and rerelease. 

I didn't expect this bug - it has to do with the fact that the compiled mod class files (Bountiful in this instance) were not compiled when the auto registrar had default method implementations - thus, Bountiful thought that it was not implementing the registration methods even though it wasn't required (but not oddly didn't know that it wasn't required). 

Seems to be a quirk with how Kotlin handles interface default implementations, it must compile them directly into inheriting subclasses.
