### ISSUE TITLE
BetterMC Kambrik-4.0-1.19.2

### ISSUE THREAD

**Issue by wenkinx** [ejektaflex/Kambrik#25] opened 2023-10-15 03:03 UTC
A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kambrik'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'kambrik'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162)
	... 2 more
Caused by: java.lang.ExceptionInInitializerError
	at io.ejekta.kambrik.internal.KambrikPrelaunch.handleCustomEntryData(KambrikPrelaunch.kt:31)
	at io.ejekta.kambrik.internal.KambrikPrelaunch.onPreLaunch(KambrikPrelaunch.kt:18)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 4 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2960 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at io.ejekta.kambrik.internal.KambrikMod.idOf(KambrikMod.kt:30)
	at io.ejekta.kambrik.logging.KambrikMarkers.createIdMarker(KambrikMarkers.kt:16)
	at io.ejekta.kambrik.logging.KambrikMarkers.<clinit>(KambrikMarkers.kt:12)
	... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 14 more
Caused by: java.lang.ClassCastException: class com.llamalad7.mixinextras.lib.apache.commons.tuple.ImmutablePair cannot be cast to class org.apache.commons.lang3.tuple.Pair (com.llamalad7.mixinextras.lib.apache.commons.tuple.ImmutablePair and org.apache.commons.lang3.tuple.Pair are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @25bbe1b6)
	at ca.fxco.memoryleakfix.config.mixinExtension.UnMixinExtension.preApply(UnMixinExtension.java:23)
	at org.spongepowered.asm.mixin.transformer.ext.Extensions.preApply(Extensions.java:156)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.preApply(TargetClassContext.java:413)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:401)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 17 more

**Comment by wenkinx** [comment] 2023-10-15 03:03
Fabric

**Comment by ejektaflex** [comment] 2023-10-15 03:10
I need the full log in order to see what's wrong. Please upload the entire file :)

**Comment by wenkinx** [comment] 2023-10-15 03:35
[latest.log](https://github.com/ejektaflex/Kambrik/files/12908529/latest.log)
我不确定是什么问题，但如果是BetterMC Fabric 1.20.1，它使用的是Kambrik-6.1.1+1.20.1-fabric.jar没有出现错误

**Comment by ejektaflex** [comment] 2023-10-15 03:43
You'll have to upload it again, the link does not seem to work. Sorry!

**Comment by wenkinx** [comment] 2023-10-15 03:47
[latest.log](https://github.com/ejektaflex/Kambrik/files/12908550/latest.log)

**Comment by ejektaflex** [comment] 2023-10-15 04:01
This seems to be caused by a crash in Memory Leak Fix. If you could remove it and test again, that would be great. I'd do it myself, but I'm currently on vacation!

**Comment by wenkinx** [comment] 2023-10-15 04:14
我很乐意帮助你测试这个问题，但是我不太确认具体操作。你的意思是删除Kambrik-4.0-1.19.2及依赖的模组重新启动查看是否出错吗。

**Comment by ejektaflex** [comment] 2023-10-15 04:17
Try delete the memory leak fix mod and run it again :)

**Comment by wenkinx** [comment] 2023-10-15 04:23
[minecraft-exported-logs-2023-10-15T12-22-01.log](https://github.com/ejektaflex/Kambrik/files/12908597/minecraft-exported-logs-2023-10-15T12-22-01.log)
我禁用了它，但提示我引起了未知的错误

**Comment by ejektaflex** [comment] 2023-10-15 04:31
This seems to be a duplicate of #24 . Memory Leak Fix is causing a crash.

You might want to try a new version, which is located only on Modrinth:
https://modrinth.com/mod/memoryleakfix/versions

Otherwise, you'll have to report it on their issue tracker. Thanks :)

**Closed as completed by ejektaflex** 2023-10-15 04:31 UTC
Labels: needs response
